export default {
  defaults: {
    state: 'WY',
    type: 'LLC',
    companyName: ''
  },

  requiredItems: [
    {
      id: 'filing_fee',
      name: 'Filing Fee',
      cost: 150
    },
    {
      id: 'ein',
      name: 'Employer Identification Number (EIN)',
      cost: 100
    },
    {
      id: 'legal_templates',
      name: 'Legal Document Templates',
      cost: 100
    },
    {
      id: 'registered_agent',
      name: 'Registered agent',
      cost: 150
    },
    {
      id: 'business_phone_address',
      name: 'Phone Number & Business Address',
      cost: 150
    },
    {
      id: 'itin',
      name: 'Individual Tax ID Number (ITIN)',
      cost: 150
    },
    {
      id: 'annual_irs_forms',
      name: 'Annual IRS Forms',
      cost: 300
    },
  ],

  addOns: {
    speedy: {
      id: 'speedy',
      name: 'Speedy filing',
      cost: 99
    }
  },

  companies: [
    {
      abbr: 'LLC',
      name: 'Limited Liability Corporation',
    },
    {
      abbr: 'INC',
      name: 'Corporation',
    }
  ],

  states: [
    {
      abbr: 'AL',
      name: 'Alabama',
      filingFee: 200,
      annualFee: 100
    },
    {
      abbr: 'AK',
      name: 'Alaska',
      filingFee: 250,
      annualFee: 0
    },
    {
      abbr: 'AZ',
      name: 'Arizona',
      filingFee: 50,
      annualFee: 0
    },
    {
      abbr: 'AR',
      name: 'Arkansas',
      filingFee: 45,
      annualFee: 150
    },
    {
      abbr: 'CA',
      name: 'California',
      filingFee: 70,
      annualFee: 800
    },
    {
      abbr: 'CO',
      name: 'Colorado',
      filingFee: 50,
      annualFee: 10
    },
    {
      abbr: 'CT',
      name: 'Connecticut',
      filingFee: 120,
      annualFee: 80
    },
    {
      abbr: 'DE',
      name: 'Delaware',
      filingFee: 90,
      annualFee: 300
    },
    {
      abbr: 'FL',
      name: 'Florida',
      filingFee: 125,
      annualFee: 138.75
    },
    {
      abbr: 'GA',
      name: 'Georgia',
      filingFee: 100,
      annualFee: 50
    },
    {
      abbr: 'HI',
      name: 'Hawaii',
      filingFee: 50,
      annualFee: 15
    },
    {
      abbr: 'ID',
      name: 'Idaho',
      filingFee: 100,
      annualFee: 0
    },
    {
      abbr: 'IL',
      name: 'Illinois',
      filingFee: 150,
      annualFee: 75
    },
    {
      abbr: 'IN',
      name: 'Indiana',
      filingFee: 95,
      annualFee: 0
    },
    {
      abbr: 'IA',
      name: 'Iowa',
      filingFee: 50,
      annualFee: 0
    },
    {
      abbr: 'KS',
      name: 'Kansas',
      filingFee: 160,
      annualFee: 50
    },
    {
      abbr: 'KY',
      name: 'Kentucky',
      filingFee: 40,
      annualFee: 15
    },
    {
      abbr: 'LA',
      name: 'Louisiana',
      filingFee: 100,
      annualFee: 35
    },
    {
      abbr: 'ME',
      name: 'Maine',
      filingFee: 175,
      annualFee: 85
    },
    {
      abbr: 'MD',
      name: 'Maryland',
      filingFee: 100,
      annualFee: 300
    },
    {
      abbr: 'MA',
      name: 'Massachusetts',
      filingFee: 500,
      annualFee: 500
    },
    {
      abbr: 'MI',
      name: 'Michigan',
      filingFee: 50,
      annualFee: 25
    },
    {
      abbr: 'MN',
      name: 'Minnesota',
      filingFee: 155,
      annualFee: 0
    },
    {
      abbr: 'MS',
      name: 'Mississippi',
      filingFee: 50,
      annualFee: 0
    },
    {
      abbr: 'MO',
      name: 'Missouri',
      filingFee: 50,
      annualFee: 0
    },
    {
      abbr: 'MT',
      name: 'Montana',
      filingFee: 70,
      annualFee: 20
    },
    {
      abbr: 'NE',
      name: 'Nebraska',
      filingFee: 105,
      annualFee: 0
    },
    {
      abbr: 'NV',
      name: 'Nevada',
      filingFee: 425,
      annualFee: 350
    },
    {
      abbr: 'NH',
      name: 'New Hampshire',
      filingFee: 100,
      annualFee: 100
    },
    {
      abbr: 'NJ',
      name: 'New Jersey',
      filingFee: 125,
      annualFee: 75
    },
    {
      abbr: 'NM',
      name: 'New Mexico',
      filingFee: 50,
      annualFee: 0
    },
    {
      abbr: 'NY',
      name: 'New York',
      filingFee: 200,
      annualFee: 0
    },
    {
      abbr: 'NC',
      name: 'North Carolina',
      filingFee: 125,
      annualFee: 200
    },
    {
      abbr: 'ND',
      name: 'North Dakota',
      filingFee: 135,
      annualFee: 50
    },
    {
      abbr: 'OH',
      name: 'Ohio',
      filingFee: 99,
      annualFee: 0
    },
    {
      abbr: 'OK',
      name: 'Oklahoma',
      filingFee: 100,
      annualFee: 25
    },
    {
      abbr: 'OR',
      name: 'Oregon',
      filingFee: 100,
      annualFee: 100
    },
    {
      abbr: 'PA',
      name: 'Pennsylvania',
      filingFee: 125,
      annualFee: 7,
      annualFeeNotes: 'Annual fee is $70 every 10 years'
    },
    {
      abbr: 'RI',
      name: 'Rhode Island',
      filingFee: 150,
      annualFee: 50
    },
    {
      abbr: 'SC',
      name: 'South Carolina',
      filingFee: 110,
      annualFee: 0
    },
    {
      abbr: 'SD',
      name: 'South Dakota',
      filingFee: 150,
      annualFee: 50
    },
    {
      abbr: 'TN',
      name: 'Tennessee',
      filingFee: 300,
      annualFee: 300
    },
    {
      abbr: 'TX',
      name: 'Texas',
      filingFee: 300,
      annualFee: 0
    },
    {
      abbr: 'UT',
      name: 'Utah',
      filingFee: 70,
      annualFee: 20
    },
    {
      abbr: 'VT',
      name: 'Vermont',
      filingFee: 125,
      annualFee: 35
    },
    {
      abbr: 'VA',
      name: 'Virginia',
      filingFee: 100,
      annualFee: 50
    },
    {
      abbr: 'WA',
      name: 'Washington',
      filingFee: 200,
      annualFee: 60
    },
    {
      abbr: 'WV',
      name: 'West Virginia',
      filingFee: 100,
      annualFee: 25
    },
    {
      abbr: 'WI',
      name: 'Wisconsin',
      filingFee: 130,
      annualFee: 25
    },
    {
      abbr: 'WY',
      name: 'Wyoming',
      filingFee: 100,
      annualFee: 50
    }
  ],

  industries: [
    '3D Printing',
    '3D Scanning',
    '3D Illustration',
    'Aerospace Engineering',
    'Aircraft Maintenance',
    'Arborist',
    'Astrology Service',
    'ATM Leasing',
    'Attorney',
    'Boat Detailing Service',
    'Boat Rental',
    'Call Center',
    'Community Initiative',
    'Equipment Rental',
    'Equipment Leasing',
    'Forestry',
    'Franchise',
    'Funeral Service',
    'Jet Ski Rental',
    'Leasing & Rental Service',
    'Leasing Business',
    'Logistics',
    'Luxury Vehicle Leasing',
    'Modelling & Talent Agency',
    'Notary Service',
    'Oil & Gas Service',
    'Personal Security Service',
    'Pest Control Service',
    'Printing Service',
    'Recycling Service',
    'Renewable Energy',
    'Residential Security',
    'Screen Printing Service',
    'Signwriting',
    'Solar Service',
    'Sports Equipment Leasing',
    'Sports Service',
    'Staffing Service',
    'Streaming Service',
    'Storage Service',
    'Utility',
    'Warehousing Service',
    'Wholesale Service',
    'Yacht Detailing Service',
    'Youth Work',
    'Auto Shop',
    'Auto Sales',
    'Auto Repair',
    'Auto Dealership',
    'Automotive',
    'Car Garage',
    'Car Parts',
    'Car Rental & Leasing',
    'Car Sales',
    'Car Wash',
    'Detail Service',
    'Mechanic',
    'Mobile Mechanic Service',
    'Repair Shop',
    'Wheels & Tires',
    'Barbershop',
    'Beauty',
    'Cosmetic Service',
    'Hair Removal Salon',
    'Hair Salon',
    'Hair Styling Service',
    'Hairdressing',
    'Microblading Service',
    'Mobile Nail Technician',
    'Nail Salon',
    'Cleaning Service',
    'Commercial Cleaning',
    'Dry Cleaning Service',
    'Home Cleaning',
    'Housekeeping Service',
    'Janitorial Service',
    'Laundromat',
    'Laundry Service',
    'Office Cleaning Service',
    'Office Organizing Service',
    'Residential Cleaning',
    'Air Conditioning Contractor',
    'Appliance (Service & Repair)',
    'Awning Installation',
    'Bathroom Remodeling Service',
    'Broadband Installation',
    'Builder',
    'Building Contractor',
    'Building Safety Inspection',
    'Carpentry',
    'Carpet & Rug Cleaning Service',
    'Construction',
    'Contractor',
    'DIY Service',
    'Excavation Service',
    'Electrician',
    'Fencing Service',
    'Flooring & Tile Contractor',
    'Flooring Supplier/Service',
    'Gardening Service',
    'General Contractor',
    'General Repair',
    'Groundwork',
    'Handyman Service',
    'Home Clearing Service',
    'Home Furnishings',
    'Home Organizing Service',
    'Home Improvement',
    'Home Moving',
    'Home Remodelling',
    'Home Renovation',
    'Home Repair & Maintenance',
    'HVAC',
    'Landscaping',
    'Lawn Care Service',
    'Locksmith Service',
    'Painting & Decorating Service',
    'Painting Service',
    'Plumbing Contractor',
    'Pool Maintenance Service',
    'Roofing Contractor',
    'Safety & Inspection Service',
    'Solar Panel Installation',
    'Tree Care Service',
    'Waste Collection',
    'Waste Disposal',
    'Waste Removal Service',
    'Window Tinting',
    'Windows & Doors',
    'Advertising Agency',
    'Aerial Photography',
    'Aerial Drone Photography',
    'Architectural Photography',
    'Art Framing & Preservation Service',
    'Art Gallery',
    'Artist',
    'Author',
    'Band',
    'Bespoke Jewelry',
    'Blogging',
    'Broadcasting',
    'Content Creation',
    'Copywriting',
    'Digital Design Consultant',
    'Digital Marketing Service',
    'Digital Media Agency',
    'DJ',
    'Drone Photography',
    'Embroidery Service',
    'Entertainment Service',
    'Etsy Trader',
    'Event Photography',
    'Fashion',
    'Film Production',
    'Furniture Design',
    'Graphic Design Service',
    'Hand-crafted Goods',
    'Influencer',
    'Interior Decorator',
    'Interior Design',
    'Media Agency',
    'Media Consultant',
    'Media Service',
    'Motion Picture Production',
    'Music Production',
    'Music Record Label',
    'Musician',
    'Photography Service',
    'Podcasting',
    'Product Photography',
    'Production Service',
    'Publishing',
    'Recording Studio',
    'Social Media Influencer',
    'Social Media Management',
    'Sports Photography',
    'Street Performer',
    'Videographer',
    'Web Design Service',
    'Wedding Photography',
    'Woodworking',
    'Basic Life Support Training',
    'Coaching',
    'Early Years Education',
    'Education Enrichment Service',
    'Education & Training Service',
    'Dance School',
    'Dance Instructor',
    'Drivers Ed Teacher',
    'Driving School',
    'EdTech',
    'Flight School',
    'Kindergarten',
    'Martial Arts Teacher',
    'Mentoring',
    'Music Teacher',
    'Professional Coaching',
    'Teacher',
    'Training Service',
    'Tutoring Service',
    'Yoga Teacher',
    'Agriculture',
    'Beekeeping',
    'Farming',
    'Fishing',
    'Hunting',
    'Sustainable Farming',
    'Accountancy Service',
    'Bookkeeping Service',
    'Debt Counseling Service',
    'Debt Service',
    'Digital Currency Service',
    'FinTech Consultant',
    'Financial Coaching',
    'Financial Consultant',
    'Financial Planning',
    'Financial Service',
    'Investment Advisor',
    'Mortgage Advice',
    'Mortgage Brokerage',
    'Payment Collections Agency',
    'Payment Processing Service',
    'Payroll Service',
    'Private Equity',
    'Venture Capital Service',
    'Wealth Management Service',
    'Bakery',
    'Baked Goods',
    'Bar',
    'Barbeque Restaurant',
    'Bartender',
    'Breakfast Restaurant',
    'Brewery',
    'Café',
    'Carryout Restaurant',
    'Catering Service',
    'Coffee House',
    'Coffee Roasting',
    'Coffee Shop',
    'Convenience Store',
    'Craft Brewery',
    'Distillery',
    'Event Catering',
    'Events Planning Service',
    'Fast Food Restaurant',
    'Food Delivery Service',
    'Food Production',
    'Food Service',
    'Food Store',
    'Food Truck',
    'Food Vending',
    'Ice Cream Shop',
    'Italian Restaurant',
    'Juice Bar',
    'Liquor Store',
    'Live Music Venue',
    'Meal Delivery Service',
    'Meal Preparation Service',
    'Mexican Restaurant',
    'Microbrewery',
    'Mixology',
    'Mobile Catering',
    'Nightclub',
    'Party Rental Service',
    'Pizzeria',
    'Restaurant',
    'Seafood Restaurant',
    'Special Events',
    'Steakhouse',
    'Takeout Food Service',
    'Vape Shop',
    'Wedding Service',
    'Winery',
    'Acupuncture',
    'Apothecary',
    'Aromatherapy',
    'Audiology Service',
    'Chiropractor',
    'Counseling Service',
    'Dentistry',
    'Doctors Practice',
    'Doula Service',
    'Drug & Alcohol Recovery Service',
    'Elderly Care Home',
    'Elderly Care Service',
    'Fitness Center',
    'Fitness Service',
    'Fitness Coaching',
    'Fitness Training',
    'Fitness & Nutrition Coaching',
    'Gym',
    'Healing Service',
    'HealthTech',
    'Health Service',
    'Health & Wellbeing Service',
    'Healthcare',
    'Healthcare Consultant',
    'Holistic Service',
    'Home Care Agency',
    'Home Healthcare',
    'Hospice Service',
    'Hospital',
    'Hypnobirthing',
    'Life Coaching',
    'Massage Therapy',
    'Medical Center',
    'Medical Practice',
    'Medical Service',
    'Medical Supplies & Equipment',
    'Medical Technology',
    'Mental Health Service',
    'Nursing Home',
    'Nursing Service',
    'Occupational Therapy',
    'Optician',
    'Optometrist Service',
    'Orthodontist',
    'Osteopathic Service',
    'Outpatient Service',
    'Personal Trainer',
    'Pharmacy',
    'Pharmaceutical Service',
    'Physical Therapy Service',
    'Physician',
    'Psychotherapy',
    'Pilates Studio',
    'Podiatrist Service',
    'Psychiatric Service',
    'Psychological Service',
    'Rehabilitation Service',
    'Relationship Therapy',
    'Social Work',
    'Spa',
    'Speech and Language Service',
    'Therapy Service',
    'Walk-In Clinic',
    'Wellness Coaching',
    'Wellness Service',
    'Antiques',
    'Apparel',
    'Auctioneering',
    'Bookstore',
    'Bridal Boutique',
    'Clothing Store',
    'Clothing Brand',
    'Clothing Alteration Service',
    'Drop Shipping',
    'Electronic Sales & Repair',
    'Firearms (Sales/Training/Education)',
    'Florist',
    'Import/Export Goods',
    'Jewelry Shop',
    'Manufacturing',
    'Manufacturing Clothes',
    'Metal Fabrication',
    'Musical Instruments & Supplies',
    'Retail Arbitrage',
    'Retail Store',
    'Sale of Alcohol or Tobacco Products',
    'Specialty Retail',
    'Tattoo & Body Piercing',
    'Tattoo Shop',
    'Welding',
    'Resale',
    'Upholstery Service',
    'Vending Machine',
    'Animal Breeding',
    'Dog Boarding',
    'Dog Breeding',
    'Dog Training Service',
    'Dog Walking Service',
    'Doggy Day-care',
    'Pet Care Service',
    'Pet Grooming',
    'Pet Boarding',
    'Pet Store',
    'Pet Training',
    'Veterinarian',
    'Admin Service',
    'Advertising Consultant',
    'Architect Service',
    'Attorney',
    'Aviation Consultant',
    'Babysitting Service',
    'Breastfeeding Consultant',
    'Business Consultant',
    'Business Development Consultant',
    'Childcare Service',
    'Civil Engineering',
    'Compliance Consultant',
    'Creative Consultant',
    'Cyber Security Consultant',
    'Data Analyst',
    'Data Processing Service',
    'Data Science',
    'Dating & Matchmaking',
    'Digital Design Consultant',
    'Education Consultant',
    'Engineering Service',
    'Executive Recruitment',
    'Expert Witness Service',
    'FinTech Consultant',
    'Financial Consultant',
    'Freelancer',
    'Gaming',
    'Gaming Service',
    'Human Resources Consultant',
    'Human Resources Service',
    'Independent Contractor',
    'Insurance Brokerage',
    'Insurance Service',
    'Intellectual Property/Patent Service',
    'IT Consultant',
    'Language & Translation Service',
    'LegalTech',
    'Legal Service',
    'Management Consultant',
    'Management Service',
    'Marketing Consultant',
    'Marketing Service',
    'Marine Service',
    'Media Consultant',
    'Non-profit Management Service',
    'Nutrition Consultant',
    'Oil & Gas Consultant',
    'Paid Search Consultant',
    'Pilot',
    'PR Consultancy',
    'Private Investigation Service',
    'Procurement Service',
    'Recruitment Agency',
    'Recruitment Consultant',
    'Research Consultant',
    'Research Service',
    'Researcher',
    'Risk Management Service',
    'Security Service',
    'SEO Consultant',
    'SEO Service',
    'Sports Consultant',
    'Tech Consultant',
    'Telecommunications Service',
    'Trading & Investment Service',
    'Training Consultant',
    'Trust Administration Service',
    'Virtual Assistant',
    'Wellness Consultant',
    'Buy & Sell Real Estate',
    'Commercial Real Estate',
    'Flipping Houses',
    'Property Service',
    'Property Rental',
    'Property Management',
    'Real Estate Renovation',
    'Real Estate Broker',
    'Real Estate Investment',
    'Real Estate Service',
    'Rental Property',
    'Amazon Seller (FBA/FBM)',
    'eBay Trader',
    'Ecommerce',
    'Online Sales',
    'Online Store',
    'Android Development Service',
    'AI Service',
    'Cloud/Hosting Service',
    'Cyber Security Service',
    'Cryptocurrency Service',
    'Digital Transformation',
    'EdTech',
    'FinTech Service',
    'HealthTech',
    'iOS Development Service',
    'IT Service',
    'LegalTech Business',
    'Software Development Service',
    'Software Engineering',
    'Tech Business',
    'Tech Repair Service',
    'Tech Service',
    'Web Developer',
    'Commercial Goods Transportation',
    'Courier Service',
    'Delivery Service',
    'Freight',
    'Freight Brokerage',
    'Haulage',
    'Hot Shot Trucking',
    'Limousine Driver',
    'Non-emergency Transportation',
    'Shipping & Packaging',
    'Taxi Service',
    'Transport Service',
    'Transportation of Goods',
    'Truck Driving',
    'Air BnB',
    'Aviation Service',
    'B&B',
    'Campsite',
    'Country Club',
    'Eco-Tour',
    'Escape Room',
    'Golf Course',
    'Hospitality',
    'Hostel',
    'Hotel',
    'Motel',
    'Museum',
    'Travel Agency',
    'Travel Service',
    'Vacation Rental'
  ],

  legalDisclaimer: 'jobboardguru.com is owned and operated by JobBoardGuru, LLC.'
};